language: go

go:
  - 1.5.2
  - 1.6rc2
  - tip

sudo: false

addons:
  ssh_known_hosts:
    - bitbucket.org

env:
  global:
    - GO15VENDOREXPERIMENT="1"

install:
  - true

script:
  - go test -v ./...
